packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  esbuild: false

catalog:
  "@typescript/native-preview": "7.0.0-dev.20260404.1"
  vite: "^8.0.3"
  vite-plus: "^0.1.15"

minimumReleaseAge: 1440
